# Generated by Django 2.2.2 on 2019-12-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesplay', '0003_auto_20191212_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
    ]
