# Generated by Django 2.2.2 on 2019-12-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesplay', '0005_page_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
    ]
